package com.gojek.assessment.common;

public enum Operations {
    CREATE_PARKING_LOT,
    PARK,
    LEAVE,
    STATUS,
    SLOT_NUMBERS_FOR_CARS_WITH_COLOUR,
    REGISTRATION_NUMBERS_FOR_CARS_WITH_COLOUR,
    SLOT_NUMBER_FOR_REGISTRATION_NUMBER;
}

